Feature/priority update
Coveros/sonar-gherkin-plugin pull request #4
Opened 2019-08-07 18:39 UTC by jeffvoight

2019-08-07 20:19 UTC, jonaqorri requested changes

2019-08-07 20:19 UTC, jonaqorri commented on gherkin-checks/src/main/java/org/sonar/gherkin/checks/FileNameCheck.java
> +  //private static final String DEFAULT = "^[a-z][-A-Za-z0-9]*\\.feature$";
remove commented code

2019-08-07 20:19 UTC, jonaqorri commented on gherkin-checks/src/main/java/org/sonar/gherkin/checks/FileNameCheck.java
> +  private static final String DEFAULT = "^ac-\\d{5,6}\\.feature$";
\\d{1, }

2019-08-07 20:19 UTC, jonaqorri commented on gherkin-checks/src/main/java/org/sonar/gherkin/checks/OneSingleThenPerScenarioCheck.java
> +  name = "There should be one single Then step per scenario",
This is not in the major section of the Gherkin SonarQube Rules word doc you sent me....does it need to be added?

2019-08-07 20:19 UTC, jonaqorri commented on gherkin-checks/src/test/java/org/sonar/gherkin/checks/FileNameCheckTest.java
> +      .next().withMessage("Rename this file to match the regular expression: ^ac-\\d{5,6}\\.feature$")
\d{1, }

2019-08-07 22:20 UTC, msaperst commented on gherkin-checks/src/main/java/org/sonar/gherkin/checks/FileNameCheck.java
> +  private static final String DEFAULT = "^ac-\\d{5,6}\\.feature$";
I thought we said 4 or more

2019-08-08 11:38 UTC, jeffvoight commented on gherkin-checks/src/main/java/org/sonar/gherkin/checks/FileNameCheck.java
> +  private static final String DEFAULT = "^ac-\\d{5,6}\\.feature$";
Yup. 4 and more is what we're going with.

2019-08-08 11:38 UTC, jeffvoight commented on gherkin-checks/src/main/java/org/sonar/gherkin/checks/OneSingleThenPerScenarioCheck.java
> +  name = "There should be one single Then step per scenario",
It's in the doc, somewhere.

2019-08-08 11:39 UTC, jeffvoight commented on gherkin-checks/src/test/java/org/sonar/gherkin/checks/FileNameCheckTest.java
> +      .next().withMessage("Rename this file to match the regular expression: ^ac-\\d{5,6}\\.feature$")
4 or more.

2019-08-08 12:14 UTC, georgiydeliya approved these changes
lgtm

2019-08-08 12:23 UTC, merged